# synced from @nextcloud/android-config

# SPDX-FileCopyrightText: 2023-2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-FileCopyrightText: 2023 Andy Scherzinger <info@andy-scherzinger.de>
# SPDX-FileCopyrightText: 2023 Tobias Kaminsky <tobias@kaminsky.me>
# SPDX-FileCopyrightText: 2023 Álvaro Brey <alvaro@alvarobrey.com>
# SPDX-License-Identifier: GPL-3.0-or-later

name: "Validate Gradle Wrapper"
on:
    pull_request:
        branches: [ master, main, stable-* ]
    push:
        branches: [ master, main, stable-* ]

# Declare default permissions as read only.
permissions: read-all

concurrency: 
  group: validate-gradle-wrapper-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
    validation:
        name: "Validation"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
            - uses: gradle/actions/wrapper-validation@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v6.1.0